name: Continuous Integration
on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker build --tag "amtronics/todo-app:$GITHUB_SHA" .
    - run: docker run "amtronics/todo-app:$GITHUB_SHA"
  deploy:
    name: push image to dockerhub
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_name == 'module9' && github.event_name == 'pull_request'
    steps:
      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}      
      - run: docker push "amtronics/todo-app:$GITHUB_SHA"
      - run: curl -dH -X POST '${{ secrets.WEBHOOK_URL }}'
